name: Cypress Tests

on:
  pull_request:
    branches:
      - develop

jobs:
  test:
    name: Cypress Tests
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the Code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x # Ensure you're using the correct version that your project needs

      # Step 3: Install Dependencies
      - name: Install Dependencies
        run: npm install

      # Step 4: Build App (Optional, but if you need it for the tests)
      - name: Build App
        run: npm run build

      # Step 5: Run Cypress Tests
      - name: Run Cypress Tests
        run: npm run test-component # Assuming `npm run test-component` is your command for Cypress tests
