name: Deploy To Render

on:
  push:
    branches:
      - main

jobs:
  ci:
    name: Deploy To Render
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the Code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Install Dependencies
      - name: Install Dependencies
        run: |
          npm install

      # Step 3: Deploy to Render
      - name: Deploy to Render
        env:
          DEPLOY_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }} # Use your secret key for deploy
        run: |
          curl -X POST "https://api.render.com/deploy/srv-cu3cici3esus73df7f3g?key=a8IqWMCoiGU"
